### ISSUE TITLE
Are there any demos to test?

### ISSUE THREAD

**Issue by mudongliang** [yyounan/freesentry#1]
I have read  your paper. In the paper you didn't use llvm to experiment.
Are there any demos to test?

**Comment by yyounan** [comment]
Hi: 慕冬亮,

You should be able to use the example here: http://blogs.cisco.com/security/talos/freesentry as a way to test it. You do bring up a good point though, next release I’ll add some test files to repository!

The paper was written to demonstrate the idea and I ported it to LLVM for CanSecWest, that’s why you have the discrepancy between the 2 versions.

-YY

**Comment by mudongliang** [comment]
1. I will try to use the example in the paper or blog. The files in the directory - FreeSentry is not written in the format of LLVM Pass, but CIL. Will you rewrite your freesentry in the format of LLVM Pass?
2. I will try to install freesentry according to your README file. I will open issues if I have problems in installing and using this tool.  

Thanks for your reply.
